/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/paste": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/paste/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["read"];
    put?: never;
    post?: never;
    delete: operations["delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AdditionalData: components["schemas"]["AdditionalDataV1"] & {
      /** @enum {string} */
      type: "v1";
    };
    AdditionalDataV1: {
      /**
       * Format: int32
       * @description Number of iterations for the PBKDF2 key derivation
       */
      PBKDF2_ITERATIONS: number;
      /** @description Whether to burn the paste after reading it once */
      burn: boolean;
      /** @description Type of the paste */
      format: components["schemas"]["PasteFormat"];
      /** @description Base64 encoding of the Initial Vector */
      iv: string;
      /** @description Base64 encoding of the salt used */
      salt: string;
    };
    CreateData: {
      /** @description Additional data, that will be verified */
      additional_data: components["schemas"]["AdditionalData"];
      /** @description The encrypted content of the paste */
      content: string;
      /** @description The required expiry time */
      expiry: components["schemas"]["ExpiryTime"];
    };
    DeleteData: {
      /** @description The deletion token */
      token: string;
    };
    /** @enum {string} */
    ExpiryTime: "5min" | "10min" | "1h" | "1d" | "1w" | "1m" | "1y" | "never";
    /** @enum {string} */
    PasteFormat: "plain" | "source" | "markdown";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateData"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /**
             * Format: uuid
             * @description The id of the paste
             */
            id: string;
            /** @description The deletion token */
            token: string;
          };
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  read: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @description Encrypted content */
            content: string;
            /** @description Additional data */
            data: components["schemas"]["AdditionalData"];
            /**
             * Format: date-time
             * @description Expiry date
             */
            expires?: string | null;
            /** Format: uuid */
            id: string;
          };
        };
      };
      /** @description No corresponding id found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
  delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteData"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Invalid token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No corresponding id found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
}
