// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdditionalData = { "type": "v1" } & AdditionalDataV1;

export type AdditionalDataV1 = { 
/**
 * Number of iterations for the PBKDF2 key derivation
 */
PBKDF2_ITERATIONS: number, 
/**
 * Type of the paste
 */
format: PasteFormat, 
/**
 * Base64 encoding of the salt used
 */
salt: string, 
/**
 * Base64 encoding of the Initial Vector
 */
iv: string, 
/**
 * Whether to burn the paste after reading it once
 */
burn: boolean, };

export type BasicInfo = { 
/**
 * The id of the paste
 */
id: string, 
/**
 * The deletion token
 */
token: string, };

export type CreateData = { 
/**
 * Additional data, that will be verified
 */
additional_data: AdditionalData, 
/**
 * The required expiry time
 */
expiry: ExpiryTime, 
/**
 * The encrypted content of the paste
 */
content: string, };

export type DeleteData = { 
/**
 * The deletion token
 */
token: string, };

export type ExpiryTime = "5min" | "10min" | "1h" | "1d" | "1w" | "1m" | "1y" | "never";

export type PasteFormat = "plain" | "source" | "markdown";
